fms/urls.py
"""
    path('', views.home, name='home')
    path('', Home.as_view(), name='home')
    path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

urlpatterns = [
    path("", include("invoices.urls")),
    path("accounts/", include("accounts.urls")),
    path("payments/", include("payments.urls")),
    path("masters/", include("masters.urls")),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masters/urls.py
"""
path('', views.home, name='home')
path('', Home.as_view(), name='home')
path('blog/', include('blog.urls'))
"""

from django.urls import path
from masters.views import inventoryData, pincodeData, v_company_create, v_company_edit, v_company_list, v_hsn_create, v_hsn_edit, v_hsn_list, v_inventory_create, v_inventory_edit, v_inventory_list, v_pincode_create, v_pincode_list, v_user_list, v_user_create, v_user_edit, v_inventory_template, v_inventory_import

app_name = "masters"


urlpatterns = [
    # path("import/", v_import_masters, name="import_masters"),

    path("inventory/", v_inventory_list, name="inventory_list"),
    path("inventory/create/", v_inventory_create, name="inventory_create"),
    path("inventory/edit/<int:pk>/", v_inventory_edit, name="inventory_edit"),
    path("inventory/template/", v_inventory_template, name="inventory_template"),
    path("inventory/import/", v_inventory_import, name="inventory_import"),
    path("inventory/api/", inventoryData.as_view(), name="inventory_list_api"),


    path("user/", v_user_list, name="user_list"),
    path("user/create/", v_user_create, name="user_create"),
    path("user/edit/<int:pk>/", v_user_edit, name="user_edit"),
    
    path("company/", v_company_list, name="company_list"),
    path("company/create/", v_company_create, name="company_create"),
    path("company/edit/<int:pk>/", v_company_edit, name="company_edit"),

    path("pincode/", v_pincode_list, name="pincode_list"),
    path("pincode/create/", v_pincode_create, name="pincode_create"),
    path("pincode/api/", pincodeData.as_view(), name="pincode_list_api"),

    path("hsn/", v_hsn_list, name="hsn_list"),
    path("hsn/create/", v_hsn_create, name="hsn_create"),
    path("hsn/edit/<int:pk>/", v_hsn_edit, name="hsn_edit"),
]


# eof

masters/models.py
from django.db.models import (
    Model,
    DateTimeField,
    ForeignKey,
    CharField,
    BooleanField,
    CASCADE,
    FloatField,
    TextField,
    EmailField,
    IntegerField,
    ImageField,
)


class Pincodes(Model):
    pincode = IntegerField(null=False, blank=False)
    city = CharField(max_length=250, null=False, blank=False)
    state = CharField(max_length=250, null=False, blank=False)
    country = CharField(max_length=250, default="India", null=True, blank=True)
    inserted_On = DateTimeField(auto_now_add=True)
    updated_On = DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.pincode)

    class Meta:
        verbose_name = "Pincode"
        verbose_name_plural = "Pincodes"
        ordering = ["state", "city"]
        unique_together = ["pincode", "city", "state"]


class Company(Model):
    name = CharField(max_length=250, null=False, blank=False)
    address = TextField()
    pincode = ForeignKey(Pincodes, on_delete=CASCADE, null=True, blank=True)
    gstin = CharField(max_length=250, null=False, blank=False)
    mobile = CharField(max_length=10, null=True, blank=True)
    email = EmailField(null=True, blank=True)
    pan = CharField(max_length=10, null=True, blank=True)
    state = CharField(max_length=128, null=False, blank=False)
    bank = CharField(max_length=250, null=True, blank=True)
    bank_account_holder = CharField(max_length=250, null=True, blank=True)
    bank_no = CharField(max_length=250, null=True, blank=True)
    bank_ifsc = CharField(max_length=250, null=True, blank=True)
    bank_branch = TextField(null=True, blank=True)
    provider = BooleanField(default=False)
    deleted = BooleanField(default=False)
    inserted_On = DateTimeField(auto_now_add=True)
    updated_On = DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.name)

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"
        ordering = ["name"]


class HSN(Model):
    hsn_code = CharField(max_length=250, null=False, blank=False)
    description = TextField()
    inserted_On = DateTimeField(auto_now_add=True)
    updated_On = DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.hsn_code

    class Meta:
        verbose_name = "HSN"
        verbose_name_plural = "HSN"
        ordering = ["hsn_code"]


class Inventory(Model):
    name = CharField(max_length=250, null=False, blank=False)
    description = TextField(null=True, blank=True)
    rate = FloatField(null=True, blank=True)
    qty = FloatField(null=True, blank=True)
    min_stock = FloatField(default=float(0), null=True, blank=True)
    sgst = FloatField(null=True, blank=True)
    cgst = FloatField(null=True, blank=True)
    igst = FloatField(null=True, blank=True)
    hsn_id = ForeignKey(HSN, on_delete=CASCADE, null=True, blank=True)
    img = ImageField(upload_to="inventory", null=True, blank=True)
    deleted = BooleanField(default=False)
    inserted_On = DateTimeField(auto_now_add=True)
    updated_On = DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.name)

    class Meta:
        verbose_name = "Inventory"
        verbose_name_plural = "Inventories"
        ordering = ["hsn_id"]

masters/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User

from masters.models import HSN, Company, Inventory


class UserModelForm(ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "is_superuser",
            "is_active",
        ]


class UserEditModelForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]


class CompanyModelForm(ModelForm):
    class Meta:
        model = Company
        fields = ["name", "address", "gstin", "mobile", "email", "pan", "state", "bank", "bank_account_holder", "bank_no", "bank_ifsc", "bank_branch", "provider"]


class HSNModelForm(ModelForm):
    class Meta:
        model = HSN
        fields = ["hsn_code", "description"]


class InventoryModelForm(ModelForm):
    class Meta:
        model = Inventory
        fields = "__all__"

masters/views.py
import csv
import os
import threading

from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from django_filters.rest_framework import DjangoFilterBackend

from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from rest_framework.filters import OrderingFilter, SearchFilter

from fms.support import remove_office
from masters.models import HSN, Pincodes, Company, Inventory, Pincodes
from masters.serializers import CitySerializer, InventorySerializer
from masters.forms import (
    CompanyModelForm,
    HSNModelForm,
    InventoryModelForm,
    UserEditModelForm,
    UserModelForm,
)


@login_required
def v_inventory_list(request):
    inventories = Inventory.objects.all()
    return render(request, "masters/inventory/list.html", {"inventories": inventories})


@login_required
def v_inventory_create(request):
    context = {"hsn": HSN.objects.all()}
    if request.method == "POST":
        form = InventoryModelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Inventory Added Successfully")
            return redirect("masters:inventory_list")
        else:
            print(form.errors)
            for field, err in form.errors.items():
                messages.warning(
                    request, request, str(field).replace("_", " ") + " : " + str(err[0])
                )
    return render(request, "masters/inventory/create.html", context)


@login_required
def v_inventory_import(request):
    status, message, data = False, "Import Failed", {}
    csv_file = request.FILES["csv_file"]
    if csv_file:
        decoded_file = csv_file.read().decode("utf-8").splitlines()
        reader = csv.DictReader(decoded_file)
        errors = []
        for row in reader:
            try:
                form = InventoryModelForm(
                    {
                        "name": row["Name"],
                        "description": row["Description"],
                        "min_stock": row["Min Stock"],
                        "sgst": row["SGST"],
                        "cgst": row["CGST"],
                        "igst": row["IGST"],
                        "rate": row["Rate"],
                        "qty": row["Qty"],
                    }
                )

                if form.is_valid():
                    obj, created = Inventory.objects.update_or_create(
                        name=form.cleaned_data["name"],
                        defaults={
                            "name": form.cleaned_data["name"],
                            "description": form.cleaned_data["description"],
                            "min_stock": form.cleaned_data["min_stock"],
                            "sgst": form.cleaned_data["sgst"],
                            "cgst": form.cleaned_data["cgst"],
                            "igst": form.cleaned_data["igst"],
                            "rate": form.cleaned_data["rate"],
                            "qty": form.cleaned_data["qty"],
                        },
                    )
                else:
                    messages.error(request, form.errors)

            except Exception as err:
                messages.error(request, f"Error importing row: {err}")

        if not errors:
            messages.success(request, "Import Successful")
        else:
            messages.warning(request, "Import Partially Successful")
    else:
        messages.error(request, "No CSV file provided")
    return redirect("masters:inventory_list")


@login_required
def v_inventory_template(request):
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="inventories.csv"'
    writer = csv.writer(response)
    latest_records = Inventory.objects.all().order_by("qty", "min_stock")
    writer.writerow(
        ["Name", "Description", "Rate", "SGST", "CGST", "IGST", "Min Stock", "Qty"]
    )
    for record in latest_records:
        writer.writerow(
            [
                record.name,
                record.description,
                record.rate,
                record.sgst,
                record.cgst,
                record.igst,
                record.min_stock,
                "",
            ]
        )
    return response


@login_required
def v_inventory_edit(request, pk):
    inventory = get_object_or_404(Inventory, id=pk)
    if request.method == "POST":
        form = InventoryModelForm(request.POST, instance=inventory)
        if form.is_valid():
            form.save()
            messages.success(request, "Inventory Updated Successfully")
            return redirect("masters:inventory_list")
    context = {"item": inventory, "hsn": HSN.objects.all()}
    return render(request, "masters/inventory/edit.html", context)


class inventoryData(generics.ListAPIView):
    api_view = ["GET"]
    permission_classes = [IsAuthenticated]
    queryset = Inventory.objects.all()
    serializer_class = InventorySerializer
    filter_backends = [DjangoFilterBackend, OrderingFilter, SearchFilter]
    filterset_fields = [
        "id",
        "name",
        "rate",
        "qty",
        "min_stock",
        "sgst",
        "cgst",
        "igst",
    ]
    search_fields = "__all__"
    ordering_fields = "__all__"


@login_required
def v_user_list(request):
    users = User.objects.all()
    context = {"users": users}
    return render(request, "masters/user/list.html", context)


@login_required
def v_user_create(request):
    context = {}
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        form2 = UserModelForm(request.POST)
        if form.is_valid() and form2.is_valid():
            user = form.save()
            user.email = form2.cleaned_data["email"]
            user.first_name = form2.cleaned_data["first_name"]
            user.last_name = form2.cleaned_data["last_name"]
            user.is_superuser = form2.cleaned_data["is_superuser"]
            user.is_active = form2.cleaned_data["is_active"]
            user.save()
            messages.success(request, "User Added Successfully")
            return redirect("masters:user_list")
        else:
            print(form.errors)
            for field, err in form.errors.items():
                messages.warning(
                    request, str(field).replace("_", " ") + " : " + str(err[0])
                )
    return render(request, "masters/user/create.html", context)


@login_required
def v_user_edit(request, pk):
    user = get_object_or_404(User, id=pk)
    if request.method == "POST":
        form = UserEditModelForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "User Updated Successfully")
            return redirect("masters:user_list")
    context = {"user": user}
    return render(request, "masters/user/edit.html", context)


@login_required
def v_company_list(request):
    company = Company.objects.all()
    context = {"companies": company}
    return render(request, "masters/company/list.html", context)


@login_required
def v_company_create(request):
    if request.method == "POST":
        form = CompanyModelForm(request.POST)
        if form.is_valid():
            o_pincode = Pincodes.objects.filter(pincode=request.POST["pincode"]).first()
            o_company = form.save()
            o_company.pincode = o_pincode
            o_company.save()
            messages.success(request, "Company Added Successfully")
            return redirect("masters:company_list")
        else:
            print(form.errors)
            for field, err in form.errors.items():
                messages.warning(
                    request, request, str(field).replace("_", " ") + " : " + str(err[0])
                )
    return render(request, "masters/company/create.html", {})


@login_required
def v_company_edit(request, pk):
    company = get_object_or_404(Company, id=pk)
    if request.method == "POST":
        form = CompanyModelForm(request.POST, instance=company)
        if form.is_valid():
            o_pincode = Pincodes.objects.filter(pincode=request.POST["pincode"]).first()
            o_company = form.save()
            o_company.pincode = o_pincode
            o_company.save()
            messages.success(request, "Company Updated Successfully")
            return redirect("masters:company_list")
    context = {"company": company}
    return render(request, "masters/company/edit.html", context)


@login_required
def import_pincodes():
    unique_pincodes = {}
    pincode_objs = []
    pincode_filepath = os.path.join(settings.BASE_DIR, "static", "pincode.csv")
    if os.path.exists(pincode_filepath):
        with open(pincode_filepath, mode="r", newline="") as file:
            csv_reader = csv.DictReader(file)
            for row in csv_reader:
                pincode_city = remove_office(row["OfficeName"])
                if row["StateName"] not in unique_pincodes.keys():
                    unique_pincodes[row["StateName"]] = {row["Pincode"]: [pincode_city]}
                else:
                    if row["Pincode"] not in unique_pincodes[row["StateName"]].keys():
                        unique_pincodes[row["StateName"]].update(
                            {row["Pincode"]: [pincode_city]}
                        )
                    else:
                        if (
                            pincode_city
                            not in unique_pincodes[row["StateName"]][row["Pincode"]]
                        ):

masters/templates/masters/hsn/create.html
{% extends 'index.html' %}
{% block title %}Homepage{% endblock %}
{% block style %}{% endblock %}
{% block body %}
<form action="" method="post">{% csrf_token %}
  <h1>HSN COMPANY
    <button type="submit" class="btn btn-outline-cyan btn-pill" style="float: right;margin-right: auto;">
      SAVE&nbsp; &nbsp;
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="icon icon-tabler icons-tabler-outline icon-tabler-arrow-right m-0">
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <path d="M5 12l14 0" />
        <path d="M13 18l6 -6" />
        <path d="M13 6l6 6" />
      </svg></button>
    <a href="{% url 'masters:hsn_list' %}" class="btn btn-outline-cyan btn-pill"
      style="float: right;margin-right: 1rem;">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="icon icon-tabler icons-tabler-outline icon-tabler-arrow-left">
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <path d="M5 12l14 0" />
        <path d="M5 12l6 6" />
        <path d="M5 12l6 -6" />
      </svg>BACK
    </a>
  </h1>
  <div class="card">
    <div class="card-body">
      <div class="row">

        <div class="col-sm-12 col-md-4 col-lg-3">
          <label class="form-label required" for="id_hsn_code">HSN Code</label>
          <input type="text" class="form-control" name="hsn_code" id="id_hsn_code" required>
        </div>

        <div class="col-sm-12 col-md-8 col-lg-9">
          <label class="form-label required" for="id_description">Description</label>
          <input type="text" class="form-control" name="description" id="id_description" required>
        </div>

      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block script %}
{% endblock %}

masters/templates/masters/hsn/edit.html
{% extends 'index.html' %}
{% block title %}Homepage{% endblock %}
{% block style %}{% endblock %}
{% block body %}
<form action="" method="post">{% csrf_token %}
  <h1>EDIT HSN
    <button type="submit" class="btn btn-outline-cyan btn-pill" style="float: right;margin-right: auto;">
      SAVE&nbsp; &nbsp;
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="icon icon-tabler icons-tabler-outline icon-tabler-arrow-right m-0">
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <path d="M5 12l14 0" />
        <path d="M13 18l6 -6" />
        <path d="M13 6l6 6" />
      </svg></button>
    <a href="{% url 'masters:hsn_list' %}" class="btn btn-outline-cyan btn-pill"
      style="float: right;margin-right: 1rem;">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="icon icon-tabler icons-tabler-outline icon-tabler-arrow-left">
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <path d="M5 12l14 0" />
        <path d="M5 12l6 6" />
        <path d="M5 12l6 -6" />
      </svg>BACK
    </a>
  </h1>
  <div class="card">
    <div class="card-body">
      <div class="row">

        <div class="col-sm-12 col-md-4 col-lg-3">
          <label class="form-label required" for="id_hsn_code">HSN Code</label>
          <input type="text" value="{{hsn.hsn_code}}" class="form-control" name="hsn_code" id="id_hsn_code" required>
        </div>

        <div class="col-sm-12 col-md-8 col-lg-9">
          <label class="form-label required" for="id_description">Description</label>
          <input type="text" value="{{hsn.description}}"class="form-control" name="description" id="id_description" required>
        </div>

      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block script %}{% endblock %}

masters/templates/masters/hsn/list.html
{% extends 'index.html' %}
{% block title %}Homepage{% endblock %}
{% block style %}
<link
    href="https://cdn.datatables.net/v/bs5/jszip-3.10.1/dt-2.1.8/b-3.2.0/b-colvis-3.2.0/b-html5-3.2.0/fh-4.0.1/sc-2.4.3/sb-1.8.1/datatables.min.css"
    rel="stylesheet">
<style>
    .user_edit {
        cursor: pointer;
    }
</style>
{% endblock %}
{% block body %}
<div class="row">
    <div class="col-12">
        <h1>HSN MASTER
            <a href="{% url 'masters:hsn_create' %}" class="btn btn-outline-cyan btn-pill" style="float: right;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="icon icon-tabler icons-tabler-outline icon-tabler-plus">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M12 5l0 14" />
                    <path d="M5 12l14 0" />
                </svg>ADD
            </a>
        </h1>
    </div>
    <div class="col-12">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="myTable">
                <thead>
                    <th>ID</th>
                    <th>HSN CODE</th>
                    <th>DESCRIPTION</th>
                </thead>
                <tbody>
                    {% for x in hsn %}
                    <tr class="inventory_edit" data-id="{{x.id}}">
                        <td>{{x.id}}</td>
                        <td>{{x.hsn_code}}</td>
                        <td>{{x.description}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
<script
    src="https://cdn.datatables.net/v/bs5/jszip-3.10.1/dt-2.1.8/b-3.2.0/b-colvis-3.2.0/b-html5-3.2.0/fh-4.0.1/sc-2.4.3/sb-1.8.1/datatables.min.js"></script>
<script>
    let table = new DataTable('#myTable');
    let user_edit_url = `{% url 'masters:hsn_edit' 0 %}`;
    

    $(document).on("click", ".inventory_edit", function () {
        var item_id = $(this).data('id');
        var url = user_edit_url.slice(0, -2) + item_id + '/';
        window.location.href = url;
    });
</script>
<script>

</script>
{% endblock %}