accounts/urls.py
"""
path('', views.home, name='home')
path('', Home.as_view(), name='home')
path('blog/', include('blog.urls'))
"""
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import v_profile_edit, v_signup_view, v_logout_view, v_profile

app_name = "accounts"


urlpatterns = [
    path("profile/", v_profile, name="profile"),
    path("profile/edit/", v_profile_edit, name="profile_edit"),
    path("login/", auth_views.LoginView.as_view(next_page="/"), name="login"),
    path("logout/", v_logout_view, name="logout"),
    path("signup/", v_signup_view, name="signup"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

fms/urls.py
"""
    path('', views.home, name='home')
    path('', Home.as_view(), name='home')
    path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

urlpatterns = [
    path("", include("invoices.urls")),
    path("accounts/", include("accounts.urls")),
    path("payments/", include("payments.urls")),
    path("masters/", include("masters.urls")),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoices/urls.py
"""
path('', views.home, name='home')
path('', Home.as_view(), name='home')
path('blog/', include('blog.urls'))
"""

from django.urls import path
from invoices.views import invoiceData, invoiceItemsData, v_dashboard, v_invoice_create, v_invoice_fingerpost, v_invoice_generate, v_invoice_item_create, v_invoice_item_delete, v_invoice_list, v_invoice_receipt, v_invoice_update, v_invoice_pdf

app_name = "invoices"


urlpatterns = [
    path("", v_dashboard, name="dashboard"),
    path("fingerpost/<int:pk>/", v_invoice_fingerpost, name="invoice_fingerpost"),
    
    path("list/", v_invoice_list, name="invoice_list"),
    path("create/", v_invoice_create, name="invoice_create"),
    path("update/<int:pk>/", v_invoice_update, name="invoice_update"),
    path("generate/<int:pk>/", v_invoice_generate, name="invoice_generate"),
    path("receipt/<int:pk>/", v_invoice_receipt, name="invoice_receipt"),
    path("pdf/<int:pk>/", v_invoice_pdf, name="invoice_pdf"),
    
    path("item/delete/<int:pk>/", v_invoice_item_delete, name="invoice_item_delete"),
    path("item/create/<int:fk>/<int:pk>/", v_invoice_item_create, name="invoice_item_create"),
    
    path("api/", invoiceData.as_view(), name="invoice_list_api"),
    path("item/api/", invoiceItemsData.as_view(), name="invoice_items_list_api"),
]

masters/urls.py
"""
path('', views.home, name='home')
path('', Home.as_view(), name='home')
path('blog/', include('blog.urls'))
"""

from django.urls import path
from masters.views import inventoryData, pincodeData, v_company_create, v_company_edit, v_company_list, v_hsn_create, v_hsn_edit, v_hsn_list, v_inventory_create, v_inventory_edit, v_inventory_list, v_pincode_create, v_pincode_list, v_user_list, v_user_create, v_user_edit, v_inventory_template, v_inventory_import

app_name = "masters"


urlpatterns = [
    # path("import/", v_import_masters, name="import_masters"),

    path("inventory/", v_inventory_list, name="inventory_list"),
    path("inventory/create/", v_inventory_create, name="inventory_create"),
    path("inventory/edit/<int:pk>/", v_inventory_edit, name="inventory_edit"),
    path("inventory/template/", v_inventory_template, name="inventory_template"),
    path("inventory/import/", v_inventory_import, name="inventory_import"),
    path("inventory/api/", inventoryData.as_view(), name="inventory_list_api"),


    path("user/", v_user_list, name="user_list"),
    path("user/create/", v_user_create, name="user_create"),
    path("user/edit/<int:pk>/", v_user_edit, name="user_edit"),
    
    path("company/", v_company_list, name="company_list"),
    path("company/create/", v_company_create, name="company_create"),
    path("company/edit/<int:pk>/", v_company_edit, name="company_edit"),

    path("pincode/", v_pincode_list, name="pincode_list"),
    path("pincode/create/", v_pincode_create, name="pincode_create"),
    path("pincode/api/", pincodeData.as_view(), name="pincode_list_api"),

    path("hsn/", v_hsn_list, name="hsn_list"),
    path("hsn/create/", v_hsn_create, name="hsn_create"),
    path("hsn/edit/<int:pk>/", v_hsn_edit, name="hsn_edit"),
]


# eof

payments/urls.py
"""
    path('', views.home, name='home')
    path('', Home.as_view(), name='home')
    path('blog/', include('blog.urls'))
"""

from django.urls import include, path
from payments.views import InvoicePaymentData, v_invoicepayment_create, v_payment_create, v_payment_list, v_pending_payment_of_company

app_name = "payments"

urlpatterns = [
    path("", v_payment_list, name="payment_list"),
    path("create/", v_payment_create, name="payment_create"),
    path("invoice/create/", v_invoicepayment_create, name="invoicepayment_create"),
    path("payment/<int:pk>/", v_pending_payment_of_company, name="payment_pending"),
    path("payment/api/", InvoicePaymentData.as_view(), name="invoicepayment_api"),
]

templates/app_settings.html
{% load static %}
<div class="nav-item dropdown">
    <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown"
        aria-label="Open user menu">
        <span>
            <img src="{% static 'img/user.png' %}" width="110" height="32" alt="Tabler" class="navbar-brand-image">
        </span>
        <div class="d-none d-xl-block ps-2">
            <div>{{ request.user.first_name}} {{ request.user.last_name }}</div>
            <div class="mt-1 small text-secondary">{{ user.username }}</div>
        </div>
    </a>
    <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
        <a href="{% url 'accounts:profile' %}" class="dropdown-item">Profile</a>
        <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
    </div>
</div>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{{ title|default:'Laxmi Car Service' }}</title>
    <!-- CSS files -->
    <link href="{% static 'css/tabler.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/tabler-flags.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/tabler-payments.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/tabler-vendors.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/demo.min.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <style>
        @import url('https://rsms.me/inter/inter.css');

        :root {
            --tblr-font-sans-serif: 'Inter Var', -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;
        }

        body {
            font-feature-settings: "cv03", "cv04", "cv11";
        }
    </style>
    {% block style %}{% endblock %}
</head>

<body class="layout-fluid">
    <script src="{% static 'js/demo-theme.min.js' %}"></script>
    <div class="page">
        {% if request.user.is_authenticated %}
        <div class="sticky-top">

        </div>
        <!-- Navbar -->
        <header class="navbar navbar-expand-md d-print-none">
            <div class="container-xl">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu"
                    aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
                    <a href=".">
                        <img src="{% static 'img/logo.png' %}" width="110" height="32" alt="Laxmi Car Service"
                            class="navbar-brand-image">
                    </a>
                </h1>
                <div class="navbar-nav flex-row order-md-last">
                    <!-- Notification -->
                    <!-- {% include 'notification.html' %} -->

                    <!-- App Settings -->
                    {% include 'app_settings.html' %}
                </div>
                {% include 'navbar.html' %}
            </div>
        </header>
        {% endif %}
        <div class="page-wrapper">
            <div class="page-body m-2">
                <!-- <div class="container-xl"> -->
                {% block body %}{% endblock %}
                <!-- </div> -->
            </div>
        </div>
    </div>

    <!-- Tabler Core -->
    <script src="{% static 'js/tabler.min.js' %}" defer></script>
    <script src="{% static 'js/demo.min.js' %}" defer></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        {% if messages %}
        {% for message in messages %}
        toastr.{{ message.tags }}('{{ message }}')
        {% endfor %}
        {% endif %}
        
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
        
        function getRemote(remote_url, method = "GET", request_data = null, header = null, response_type = "json", convertapi = true, process_data = false, content_type = 'application/x-www-form-urlencoded; charset=UTF-8') {
            var resp = $.ajax({ type: method, data: request_data, dataType: response_type, url: remote_url, async: false, processData: process_data, contentType: content_type, headers: header }).responseText;
            if (convertapi) { return JSON.parse(resp); }
            return resp;
        }

        function rmv_secondlast(url) {
            var a = url.split('/');
            return url.replace(a[a.length - 2] + '/', '');
        }
    </script>
    {% block script %}{% endblock %}
</body>

</html>

templates/navbar.html
<div class="collapse navbar-collapse" id="navbar-menu">
    <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'invoices:dashboard' %}">
                    <span
                        class="nav-link-icon d-md-none d-lg-inline-block">
                        <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-layout-dashboard"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M5 4h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1" /><path d="M5 16h4a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1" /><path d="M15 12h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1" /><path d="M15 4h4a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1" /></svg>
                    </span>
                    <span class="nav-link-title">Dashboard</span>
                </a>
            </li>

            <!-- <li class="nav-item">
                <a class="nav-link" href="">
                    <span
                        class="nav-link-icon d-md-none d-lg-inline-block">
                        <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-truck-delivery"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M7 17m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M17 17m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M5 17h-2v-4m-1 -8h11v12m-4 0h6m4 0h2v-6h-8m0 -5h5l3 5" /><path d="M3 9l4 0" /></svg>
                    </span>
                    <span class="nav-link-title">Order</span>
                </a>
            </li> -->

            <li class="nav-item">
                <a class="nav-link" href="{% url 'invoices:invoice_list' %}">
                    <span
                        class="nav-link-icon d-md-none d-lg-inline-block">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-file-invoice">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                            <path d="M14 3v4a1 1 0 0 0 1 1h4" />
                            <path d="M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2z" />
                            <path d="M9 7l1 0" />
                            <path d="M9 13l6 0" />
                            <path d="M13 17l2 0" />
                          </svg>
                    </span>
                    <span class="nav-link-title">Invoice</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'payments:payment_list' %}">
                    <span
                        class="nav-link-icon d-md-none d-lg-inline-block">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-report-search">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                            <path d="M8 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h5.697" />
                            <path d="M18 12v-5a2 2 0 0 0 -2 -2h-2" />
                            <path d="M8 3m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v0a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z" />
                            <path d="M8 11h4" />
                            <path d="M8 15h3" />
                            <path d="M16.5 17.5m-2.5 0a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0" />
                            <path d="M18.5 19.5l2.5 2.5" />
                          </svg>
                    </span>
                    <span class="nav-link-title">Payment</span>
                </a>
            </li>
            {% if request.user.is_superuser or request.user.is_staff %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-base" data-bs-toggle="dropdown"
                    data-bs-auto-close="outside" role="button" aria-expanded="false">
                    <span
                        class="nav-link-icon d-md-none d-lg-inline-block">
                        <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-library"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M7 3m0 2.667a2.667 2.667 0 0 1 2.667 -2.667h8.666a2.667 2.667 0 0 1 2.667 2.667v8.666a2.667 2.667 0 0 1 -2.667 2.667h-8.666a2.667 2.667 0 0 1 -2.667 -2.667z" /><path d="M4.012 7.26a2.005 2.005 0 0 0 -1.012 1.737v10c0 1.1 .9 2 2 2h10c.75 0 1.158 -.385 1.5 -1" /><path d="M11 7h5" /><path d="M11 10h6" /><path d="M11 13h3" /></svg>
                    </span>
                    <span class="nav-link-title">
                        Masters
                    </span>
                </a>
                <div class="dropdown-menu">
                    <div class="dropdown-menu-columns">
                        <div class="dropdown-menu-column">
                            <!-- <a class="dropdown-item" href="">
                                Countries
                            </a> -->
                            <a class="dropdown-item" href="{% url 'masters:hsn_list' %}">
                                HSN Codes
                            </a>
                            <a class="dropdown-item" href="{% url 'masters:pincode_list' %}">
                                Pincode
                            </a>
                            <!-- <a class="dropdown-item" href="">
                                HSN Codes
                            </a> -->
                            <a class="dropdown-item" href="{% url 'masters:inventory_list' %}">
                                Inventory
                            </a>
                        </div>
                        <div class="dropdown-menu-column">
                            <a class="dropdown-item" href="{% url 'masters:user_list' %}">
                                Users
                            </a>
                            <!-- <a class="dropdown-item" href="">
                                Company Group
                            </a> -->
                            <a class="dropdown-item" href="{% url 'masters:company_list' %}">
                                Company
                            </a>
                            <!-- <a class="dropdown-item" href="">
                                Currency
                            </a> -->
                        </div>
                    </div>
                </div>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

templates/notification.html
<div class="d-none d-md-flex">
    <div class="nav-item dropdown d-none d-md-flex me-3">
        <a href="#" class="nav-link px-0" data-bs-toggle="dropdown" tabindex="-1"
            aria-label="Show notifications">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path
                    d="M10 5a2 2 0 1 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6">
                </path>
                <path d="M9 17v1a3 3 0 0 0 6 0v-1"></path>
            </svg>
            <span class="badge bg-red"></span>
        </a>
        
        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-end dropdown-menu-card">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Last updates</h3>
                </div>
                <div class="list-group list-group-flush list-group-hoverable">
                    <div class="list-group-item">
                        <div class="row align-items-center">
                            <div class="col-auto"><span
                                    class="status-dot status-dot-animated bg-red d-block"></span>
                            </div>
                            <div class="col text-truncate">
                                <a href="#" class="text-body d-block">Example 1</a>
                                <div class="d-block text-secondary text-truncate mt-n1">
                                    Change deprecated html tags to text decoration classes
                                    (#29604)
                                </div>
                            </div>
                            <div class="col-auto">
                                <a href="#" class="list-group-item-actions">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                        class="icon text-muted" width="24" height="24"
                                        viewBox="0 0 24 24" stroke-width="2"
                                        stroke="currentColor" fill="none" stroke-linecap="round"
                                        stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none">
                                        </path>
                                        <path
                                            d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z">
                                        </path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="row align-items-center">
                            <div class="col-auto"><span class="status-dot d-block"></span></div>
                            <div class="col text-truncate">
                                <a href="#" class="text-body d-block">Example 2</a>
                                <div class="d-block text-secondary text-truncate mt-n1">
                                    justify-content:between ⇒ justify-content:space-between
                                    (#29734)
                                </div>
                            </div>
                            <div class="col-auto">
                                <a href="#" class="list-group-item-actions show">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                        class="icon text-yellow" width="24" height="24"
                                        viewBox="0 0 24 24" stroke-width="2"
                                        stroke="currentColor" fill="none" stroke-linecap="round"
                                        stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none">
                                        </path>
                                        <path
                                            d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z">
                                        </path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>